#!/usr/bin/env python3
# ============================================================================
# audit-v38-ps1.py — machine audit of patches/trigger-test-v38.ps1
# (the v37 audit core, re-targeted v37->v38 as the byte-identity base,
#  PLUS the v38 checks: THE 0x2E-GUARD FIX — the D2 name-match loop must
#  decode EVERY section name with NO first-byte guard; the census
#  fallback must exist and fire only on a miss; the stale '.data'-era
#  skip label must be gone. The ABSOLUTE op-12 absence gate stands.)
# ============================================================================
import sys, re, pathlib

P = pathlib.Path('/home/z/my-project/patches/trigger-test-v38.ps1')
t = P.read_text(encoding='utf-8')
srcbase = pathlib.Path('/home/z/my-project/patches/trigger-test-v37.ps1').read_text(encoding='utf-8')
fails = []

def check(name, cond, detail=''):
    if cond: print(f'  PASS  {name}')
    else:
        print(f'  FAIL  {name} {detail}'); fails.append(name)

print('== v38 structural audit ==')

# 1. encoding / NULs / line endings
nul = t.count('\x00')
check('NUL count == 2 (the PE display bytes)', nul == 2, f'got {nul}')
check('LF-only line endings', '\r\n' not in t)
check('pure ASCII', all(ord(c) < 128 for c in t))

# 2. brace balance (absolute) + paren delta vs the v37 base (the v38
#    edits are paren-neutral by construction; prose parens are counted)
check('brace balance', t.count('{') == t.count('}'), f'{t.count("{")} vs {t.count("}")}')
d37 = srcbase.count('(') - srcbase.count(')')
d38 = t.count('(') - t.count(')')
check('paren delta == the field-run v37 base', d38 == d37, f'v37={d37} v38={d38}')

# 3. THE ABSOLUTE GATE: op-12 must NEVER be sent
sends12 = re.findall(r"New-Req\s+\S+\s+12\s", t)
check('*** op-12 sends == 0 (RETIRED — the class-kill) ***', len(sends12) == 0, str(sends12))
check('op-12 retirement note present', 'op-12 stays RETIRED' in t or 'op-12 is RETIRED' in t)
check('no stale P-ladder labels', '--- step P1:' not in t and 'step P: op 12' not in t)
check('no stale pSent/p1 variables', '$pSent' not in t and '$p1Ok' not in t and '$p1Cr3' not in t)

# 4. the gate fix (carried from v36 - must stand)
check('D1 gate accepts nsec up to 96', '$nsec -ge 1 -and $nsec -le 96' in t)
check('no live -le 24 gate remnant', '$nsec -ge 1 -and $nsec -le 24' not in t)

# 5. the D2 chunked table read (carried - must stand)
check('D2 chunk loop present', 'New-Req $d2Seq 1 ' in t)
check('D2 chunk size capped at 1024', '[Math]::Min(1024, ([uint64]$secRva + [uint64]$secLen) - $d2Off)' in t)
check('D2 assembly via List[byte]', 'New-Object System.Collections.Generic.List[byte]' in t)
check('D2 fail-closed throw on chunk failure', 'failed x3" -f $d2Off' in t)
check('D2 seq base 0x1B02', '$d2Seq  = 0x1B02' in t)
check('D2 table-fits-image bound', '(($secRva + $secLen) -le [int]$peSize)' in t)

# 6. *** THE 0x2E-GUARD FIX *** (v38's whole reason to exist)
check('*** NO first-byte 0x2E guard in the D2 match loop ***',
      'd2.Data[($si * 40)] -eq 0x2E' not in t and '-eq 0x2E' not in t)
check('*** the name decode is UNGUARDED (every name decoded) ***',
      re.search(r"for \(\$si = 0; \$si -lt \$nsec; \$si\+\+\) \{\s*\n\s*#[^\n]*\n\s*#[^\n]*\n\s*#[^\n]*\n\s*#[^\n]*\n\s*#[^\n]*\n\s*#[^\n]*\n\s*#[^\n]*\n\s*#[^\n]*\n\s*#[^\n]*\n\s*\$nm = \[System\.Text\.Encoding\]::ASCII\.GetString", t) is not None,
      'the decode must directly follow the loop header (comments allowed, guards NOT)')
check('the guard-fix story comment present', 'THE 0x2E-GUARD FIX' in t)
check('the guard-fix cites the field proof (transcript [DT] echo)',
      "byte-parsed from the v37" in t or "byte-parsed from the v37 transcript's own [DT] echo" in t)
check('*** the census fallback present ***', '[D2] census of all' in t)
check('census fires ONLY on a miss ($dataRva -eq 0)',
      t.index('if ($dataRva -eq 0) {') < t.index('[D2] census of all'))
check('census is pure decode (no driver reads between guard-fix and bounds gate)',
      'New-Req' not in t[t.index('THE 0x2E-GUARD FIX'):t.index('if ($dataRva -gt 0 -and $dataVs -gt 0')])
check('*** the stale .data-era skip label is GONE ***', 'no .data section / bounds' not in t)
check('the new skip label present', "SKIPPED (the ALMOSTRO section not found / out of bounds)" in t)
check('the audit-blindness lesson documented', 'invisible to' in t and '158-check' in t)

# 7. THE ALMOSTRO TARGET (carried)
check('*** section filter targets ALMOSTRO ***', "-eq 'ALMOSTRO'" in t)
check('*** the .data filter is GONE from the D2 loop ***', "-eq '.data'" not in t)
check('D2 print names ALMOSTRO', 'ALMOSTRO RVA=0x{0:X} size=0x{1:X} ({2} bytes) - dumping (the Mm globals cluster)' in t)
check('not-found line names ALMOSTRO', 'ALMOSTRO not found / out of bounds in the section table' in t)
check('dump basename ntoskrnl-almostro', "Join-Path $spot2 'ntoskrnl-almostro'" in t)
check('manifest header v38 + ALMOSTRO', '# ntoskrnl ALMOSTRO dump manifest - generated by trigger-test-v38' in t)
check('manifest sec_name/rva/vs labels', 'sec_name=ALMOSTRO' in t and 'sec_rva=0x{0:X}' in t and 'sec_vs=0x{0:X}' in t)
check('manifest records the R9 window', 'r9_window=0xCFC4C0..0xCFC538' in t)
check('step-D banner names ALMOSTRO', "--- step D: the ALMOSTRO dump (op-1 image-gated 1024B chunks; ~4-5 minutes; resumable) ---" in t)
check('[15a] comment tells the v38 story', 'THE ALMOSTRO DUMP (the Mm globals cluster - v38)' in t)
check('v38 header: the v37 post-mortem (12th green run)', 'THE v37 STORY (the 12th green run' in t)
check('v38 header: ONE GUARD BYTE framing', 'ONE GUARD BYTE' in t)
check('v38 header: the section map (RVA=0xCFB000 VS=0x272E0)', 'ALMOSTRO RVA=0xCFB000 VS=0x272E0' in t)
check('v38 header: the expected dump math (160480 B)', '160480 bytes' in t)

# 8. THE R9 NEIGHBORHOOD (carried)
check('R9 banner present', '--- step R9: the researched-slot neighborhood (op-1 image-gated 8B reads; 16 qwords @0xCFC4C0..0xCFC538) ---' in t)
check('R9 window base 0xCFC4C0', '$r9Base = 0xCFC4C0' in t)
check('R9 loops 16 qwords', '$r9i -lt 16' in t)
check('R9 send shape (op-1 gated 8B, seq continues)', "Send-Req (New-Req $seqR 1 'FFFFFFFF' 8 ('{0:X16}' -f ($peBase + [uint64]$r9Rva)) $null)" in t)
check('R9 rSent counts', t.count('$rSent++') == 5, str(t.count('$rSent++')))
check('R9 canaries', 'Canary ("pre-R9-" + [string]$r9i)' in t)
check('R9 shape classifier (image/kernel/aligned/residue)', "'in-IMAGE ptr'" in t and "'KERNEL ptr'" in t and 'PAGE-ALIGNED res=0x{0:X}' in t)
check('R9 fail line (fail-closed)', 'R9+0x{0:X2}] @0x{1:X} FAIL: no data' in t)

# 9. THE PRE-SCAN (carried - byte-identical region)
check('pre-scan banner', "--- step D+: the ALMOSTRO pre-scan (in-script, no driver reads) ---" in t)
check('pre-scan guarded by dumpOk', 'if ($dumpOk) {' in t and 'the v38 PRE-SCAN (pure PowerShell' in t)
check('pre-scan reads the .bin from disk', '[System.IO.File]::ReadAllBytes($dumpPath)' in t)
check('pre-scan size gate (== section vs)', '$db.Length -eq [int64]$dataVs' in t)
check('pre-scan qword array via BitConverter', "[UInt64]([BitConverter]::ToUInt64($db, $i * 8))" in t)
check('candidate shape: page-aligned + canonical + non-image', '($v -band [UInt64]0xFFF) -eq [UInt64]0' in t and "'0xFFFF800000000000'" in t)
check('candidate objects pscustomobject', '[pscustomobject]@{ o = ($i * 8); v = $v; r = [int]($v % [UInt64]48) }' in t)
check('candidate count line', 'pdb value candidates (page-aligned, canonical, non-image): {0}' in t)
check('lattice window scan (128B / 16 qwords)', '$k -lt 16' in t and 'while ($wi -le ($db.Length - 128))' in t)
check('lattice link condition >=3', '$bestN -ge 3' in t)
check('lattice self-link condition >=2', '$self -ge 2' in t)
check('lattice self-link UInt64-safe target (v-peLo IS the RVA)', '$tgt = $v - $peLo' in t)
check('lattice self-link target NOT double-offset', '($v - $peLo) + [UInt64]$dataRva' not in t)
check('lattice window print', 'LATTICE WINDOW dump 0x{0:X} rva 0x{1:X}: res=0x{2:X} links={3} selflinks={4}' in t)
check('lattice residues collected', '$latRes[$bestR] = $true' in t)
check('no-lattice fallback line', 'no lattice window found (the offline analysis re-scans the .bin anyway)' in t)
check('candidate print residue-tagged', 'cand dump 0x{0:X6} rva 0x{1:X6} val 0x{2:X16} res 0x{3:X2}{4}' in t)
check('lattice-match tag', '<-- LATTICE-MATCH' in t)
check('candidate print capped at 40', 'if ($shown -ge 40)' in t)
check('echo check 1 (MmPteBase slot vs live R1)', 'RVA 0xCFB358, the MmPteBase slot' in t)
check('echo check 2 (PsInitialSystemProcess slot vs W1 eproc)', 'RVA 0xCFC420, the PsInitialSystemProcess slot' in t)
check('echo check 2 uses $wSys', '$wSys)' in t)
check('pre-scan try/catch (harmless-by-design)', 'pre-scan threw: {0} (harmless - the .bin is what matters)' in t)

# 10. THE F4-BRACE FIX carried (the F4 verdict at top level)
i_f3partial = t.index('} elseif ($anOk -and $wCount -ge 1) {')
i_f3not     = t.index('>>> F3 NOT PROVEN THIS RUN')
i_f4assign  = t.index('$f4Ok = $anOk -and $reconPteOk -and $dumpOk')
check('*** F4 verdict at TOP LEVEL (after the F3 chain) ***', i_f3partial < i_f3not < i_f4assign,
      f'{i_f3partial} {i_f3not} {i_f4assign}')
check('*** no $f4Ok inside the F3-PARTIAL branch ***', '$f4Ok' not in t[i_f3partial:i_f3not])
check('F4 verdict text (RECON-2 + ALMOSTRO)', '>>> F4 RECON-2 COMPLETE + THE ALMOSTRO CLUSTER CAPTURED' in t)
check('F4 verdict cites the lattice method', 'page-list lattice: every Mm list link is pdb + pfn*0x30' in t)
check('F4 partial verdict fail-closed language', 'F4 RECON-2 PARTIAL' in t and 'alive by construction' in t)
check('the brace-bug story documented', 'nested it inside the F3-PARTIAL branch' in t)

# 11. the W-wire: 4 op-11 sends, byte-identical to v37
w = re.findall(r"New-Req (0x19[0-9A-Fa-f]{2}) 11 (\S+) (\d+) '([0-9]{16})' \$null", t)
check('W sends found (4)', len(w) == 4, str(w))
seqs = [x[0] for x in w]
check('W seqs 0x1901..0x1904 unique', sorted(set(seqs)) == ['0x1901','0x1902','0x1903','0x1904'], str(seqs))
check('W1/W4a/W4b/W5 pid fields', w[0][1] == "'FFFFFFFF'" and w[3][1] == '$myPid', str([x[1] for x in w]))
check('W4 outN gate values', w[1][2] == '0' and w[2][2] == '33', str([x[2] for x in w]))

# 12. the M-wire byte-identical to v37
mbase = re.findall(r"Send-Resolve (0x18[0-9A-Fa-f]{2}) '([^']+)'", srcbase)
m38 = re.findall(r"Send-Resolve (0x18[0-9A-Fa-f]{2}) '([^']+)'", t)
check('M-wire identical to v37 (4 sites)', mbase == m38 and len(m38) == 4, f'{m38}')

# 13. the op-11 payload decode offsets + the dtb echo
for off, label in ((1024,'status'),(1028,'count'),(1032,'sys'),(1040,'nameOfs'),
                   (1044,'closed'),(1048,'pages'),(1052,'stored')):
    check(f'payload offset {label}@{off}', f'U32 $W1.Data {off}' in t or f'U64 $W1.Data {off}' in t)
check('dtb@1056 echo parsed', 'U64 $W1.Data 1056' in t)

# 14. THE RECON WIRE (R1..R7 unchanged)
rseqs = re.findall(r"Send-Req \(New-Req \$seqR 1 'FFFFFFFF' 8 \('\{0:X16\}' -f \(\$peBase \+ \[uint64\]\$cd\.rva\)\) \$null\)", t)
check('R-loop send shape (the cands table drives it)', len(rseqs) == 1, str(len(rseqs)))
for k, rva in (('R1','0xCFB358'),('R2','0xCFA358'),('R3','0xCFC508'),
               ('R4','0xCFC500'),('R5','0xCFC510'),('R6','0xCFB500'),('R7','0xCFB508')):
    check(f'cand {k} rva {rva}', f"n='{k}'; rva={rva}" in t, f'cand {k}')
check('recon seq base 0x1A01', '$seqR = 0x1A01' in t)
check('PS shape mirror: bits38:0 == 0', "'0x0000007FFFFFFFFF'" in t)
check('PS shape mirror: hi == 0xFFFF', '-shr 48' in t)
check('collision guard s=0x100 (MmSystemRangeStart)', '($sIx -eq 0x100)' in t and 'MmSystemRangeStart' in t)
check('collision guard s=0x1EF (KUSD)', '($sIx -eq 0x1EF)' in t)
check('the deadly-arithmetic display (pdb + pfn*0x30 + 8)', '$pfnIx * 0x30' in t and 'pdb + {1}*0x30 + 8' in t)
check('R8 = the W dtb echo cross-display', '--- step R8: the System DTB' in t)
check('recon canaries', "Canary (\"pre-\" + $cd.n)" in t)

# 15. THE DUMP WIRE (D0/D1 + the loop) — carried
check('D0 self-verify: 1024B @ pe_base + MZ + e_lfanew == L2a', 'New-Req 0x1B00' in t and
      "$d0.Data[0] -eq 0x4D -and $d0.Data[1] -eq 0x4A" not in t and
      "$d0.Data[0] -eq 0x4D -and $d0.Data[1] -eq 0x5A" in t and
      '((U32 $d0.Data 0x3C) -eq [uint32]$lfanew)' in t)
check('D1 section header read (20B @ lfanew+4)', 'New-Req 0x1B01' in t)
check('section parse fields (VS@+8, VA@+12)', '($si * 40 + 8)' in t and '($si * 40 + 12)' in t)
check('dump bounds gate (rva+vs <= peSize)', '($dataRva + $dataVs) -le [int]$peSize' in t)
check('chunk size 1024', '$chunkSz  = 1024' in t)
check('dump loop dynamic seq (0x2000 + chunk)', '(0x2000 + $ci)' in t)
check('dump retry x3 + sleep', 'for ($try = 1; $try -le 3; $try++)' in t and 'Start-Sleep -Milliseconds 150' in t)
check('dump resume marker (pe_base bound)', 'pe_base=0x{0:X};rva=0x{1:X};vs=0x{2:X};chunk={3}' in t)
check('resume only on identical marker', '"$mkOld" -eq "$mkTxt"' in t)
check('resume append mode', "'Append')" in t)
check('fresh dump starts a new marker', '[System.IO.File]::WriteAllText($mkPath, $mkTxt)' in t)
check('progress line + ETA', 'ETA~{4}m{5:d2}s' in t)
check('sha256 of the dump', 'Get-FileHash -Algorithm SHA256' in t)
check('manifest written with recon RVAs + w_dtb', '.manifest.txt' in t and 'recon_{0}_rva=0x{1:X}' in t)
check('dumpSent increments in the loop', t.count('$dumpSent++') == 1, str(t.count('$dumpSent++')))
check('dump fail-closed stop (failAt)', '$failAt = $ci; break' in t)
check('send-the-dump instruction', 'SEND THE .bin + .manifest.txt + this .txt' in t)

# 16. W2 exit-race tolerance — carried
check('W2 re-query on missing pid', 'Get-Process -Id ([int]$ep) -ErrorAction Stop' in t)
check('W2 EXITED tolerance text', 'EXITED between walk and snapshot (tolerated, v35)' in t)
check('W2 threshold missing -le 1', '($missing -le 1) -and ($cntDelta -le 3)' in t)
check('W2 CAP-AWARE expected value', '$liveCap = [Math]::Min($liveProcs.Count, 64)' in t)

# 17. step 0 (full bugcheck args + the CONFIRMED fingerprint)
check('step0 message truncation 420', '$m.Length -gt 420' in t)
check('step0 args regex extract', "bugcheck was:\\s*(0x[0-9a-fA-F]+)\\s*\\(([^)]+)\\)" in t)
check('step0 both-crashes-confirmed hint (v38)', '<- v38: the v33+v34 0x50s are BOTH fingerprint-CONFIRMED' in t)
check('step0 the arithmetic stated for NEW crashes', '0x5078 = 0x1AD*0x30+8 = chain B' in t)
check('step0 minidump hint', 'C:\\Windows\\Minidump' in t)

# 18. INFCNT dynamic accounting (rSent now includes R9 + D0/D1/D2)
check('expFinal includes rSent + dumpSent', '$cntVal + 8 + $anSent + $mNameWrites + $wSent + $rSent + $dumpSent' in t)
line = [l for l in t.splitlines() if 'INFCNT final = {0}' in l]
check('INFCNT printf line exists', bool(line))
if line:
    m = re.search(r'-f (.+)$', line[0])
    check('INFCNT printf has -f', bool(m))

# 19. canaries
for c in ('pre-W1', 'pre-W4', 'pre-W5'):
    check(f"canary {c}", f"Canary '{c}'" in t)
for c in ('pre-M1','pre-M2r','pre-M3','pre-M4'):
    check(f'canary {c}', f"Canary '{c}'" in t)
for c in ('pre-D0','pre-D1','pre-D2'):
    check(f'canary {c} (the dump gates)', f"Canary '{c}'" in t)

# 20. verdict + summary + END
check('F3 verdict block intact', '>>> F3 PROVEN: THE EPROCESS WALK' in t)
check('F3 PROVEN next-line updated', "Next: F4 (the ALMOSTRO constants + the walk), then Infinity.exe." in t)
check('[15] summary line (R1..R9)', '"[15] F4 constants recon (R1..R9) : {0}" -f $f4Sum' in t)
check('[14] cites the v36 field', '(v36 field: the cap-aware W2 PASSed)' in t)
check('END v38 marker', "Write-Host '==== END v38 ===='" in t)
check('no stale v37 END', '==== END v37 ====' not in t)
check('wSent increments == 4', t.count('$wSent++') == 4, str(t.count('$wSent++')))

# 21. driver-ID texts (v26 UNCHANGED is correct for the 6th run)
check('v26-RT = 140582 documented', '140582' in t)
check('v38 is script-only / v26 unchanged 6th run', 'SCRIPT-ONLY' in t and 'UNCHANGED' in t and '6th run' in t)
check('the v26 sha256 documented', 'c8f79b95' in t and '921bb' in t)
check('driver-ID: UNCHANGED from v37', 'UNCHANGED from v37 (memory.efi v26 RT,' in t)

# 22. step positions: R after W, R9 after R8, D after R, D+ after D, N after D
iw  = t.index('--- step W5')
ir  = t.index('--- step R: the constant RECON')
ir9 = t.index('--- step R9:')
idm = t.index('--- step D: the ALMOSTRO dump')
idp = t.index('--- step D+: the ALMOSTRO pre-scan')
inn = t.index('--- step N: final INFCNT read')
check('W5 < R < R9 < D < D+ < N', iw < ir < ir9 < idm < idp < inn)

# 23. the regression core byte-identical vs v37: K wire + J ladder + L reads
kbase = re.findall(r"Send-Req \(New-Req 0x170[0-9A-Fa-f] 9 [^\n]+", srcbase)
k38 = re.findall(r"Send-Req \(New-Req 0x170[0-9A-Fa-f] 9 [^\n]+", t)
check('K wire (op-9) byte-identical to v37', kbase == k38 and len(k38) >= 1, f'{len(kbase)} vs {len(k38)}')
jbase = re.findall(r"n = 'J[0-9]';[^\n]+", srcbase)
j38 = re.findall(r"n = 'J[0-9]';[^\n]+", t)
check('J ladder rows byte-identical to v37 (7 rows)', jbase == j38 and len(j38) == 7, f'{len(jbase)} vs {len(j38)}')
lbase = re.findall(r"Send-Req \(New-Req 0x17[0-9A-Fa-f]{2} 1 [^\n]+", srcbase)
l38 = re.findall(r"Send-Req \(New-Req 0x17[0-9A-Fa-f]{2} 1 [^\n]+", t)
check('L-step op-1 reads byte-identical to v37', lbase == l38, f'{len(lbase)} vs {len(l38)}')

# 24. selftest preserved
check('selftest DEADBEEF intact', "ST-Check ($stLe.Length -eq 4 -and $stLe[0] -eq 0xEF" in t)
check('startup selftest gate', 'SELFTEST][ABORT' in t)

# 25. W1 expectations intact
check('eproc OUT-OF-IMAGE gate (THE F3 claim)', '$eprocOutside = ($wSys -lt $peBase) -or ($wSys -ge ($peBase + $peSize))' in t)
check('out-of-image PASS text', 'PROCESS DATA OUTSIDE THE IMAGE - the F3 claim itself' in t)

# 26. transcript + banner
check('transcript v38 name', 'trigger-test-v38-output-' in t)
check('banner v38', "Write-Host '==== INFINITY trigger test v38 (" in t)
check('no stale v37 banner', "Write-Host '==== INFINITY trigger test v37 (" not in t)

print()
if fails:
    print(f'== {len(fails)} FAILURES ==')
    for f in fails: print(f'  - {f}')
    sys.exit(1)
print('== ALL CHECKS PASS ==')
